### PR TITLE
Multiple improvements

### PR DESCRIPTION
**Pull request by baptisterajaut**
Good day mate, i stumbled upon your simple yet efficient project, i use it now in my company so i brang my improvements
- I fixed the docker image by using a python 3.9 image (alpine now uses 3.11 and it breaks gunicorn)
- while i was at it i put the app in a separate folder, instead of packaging the scripts and dockerfile for nothing
- i prevented the overwriting of existing image name
- and i added a virtualhost example for apache2

Enjoy matey

### CODE REVIEW

**Comment by gechandesu** [comment]
Thank you for your interest in the project, I'm glad that imgs was useful.

You suggested good improvements, I myself have long planned to make something similar. Some of the proposed I want to do differently, so I will make changes in the new version.

**Comment by baptisterajaut** [comment]
G'day mate. Seems you haven't had the time to work on imgs. Could you at least accept the merge request for now?

**Comment by baptisterajaut** [comment]
Hey mate, i even added a new feature.

**Comment by baptisterajaut** [comment]
Hey you know what, i'm okay with maintaining it now. If you have time, just put my fork in your readme.

**Pull request closed without merging**
